version: '3.9'

services:
  cardano-explorer-api:
    container_name: cardano-explorer-api
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - HOST_DB=${HOST_DB}
      - PORT_DB=${PORT_DB}
      - USERNAME_DB=${USERNAME_DB}
      - PASSWORD_DB=${PASSWORD_DB}
    ports:
      - "8033:8080"
    volumes:
      - $PWD/cardano/volumes/logs/cardano-explorer-api:/cardano-explorer-api/logs/

    networks:
      - infrastructure-net

  redis-master:
    hostname: cardano.redis.master
    container_name: cardano-redis-master
    image: redis:7.0.5
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=redis_password
    command: redis-server
    ports:
      - "26301:6379"
    deploy:
      resources:
        limits:
          memory: 2048m

  redis-slave:
    hostname: cardano.redis.slave
    container_name: cardano-redis-slave
    image: redis:7.0.5
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=redis_password
      - REDIS_PASSWORD=redis_slave_pass
    command: redis-server --slaveof redis-master 6379
    ports:
      - "26302:6379"
    links:
      - redis-master
    deploy:
      resources:
        limits:
          memory: 2048m

  redis-sentinel:
    hostname: cardano.redis.sentinel
    container_name: cardano-redis-sentinel
    image: 'bitnami/redis-sentinel'
    environment:
      - REDIS_MASTER_HOST=127.0.0.1
      - REDIS_MASTER_PORT_NUMBER=26301
      - REDIS_MASTER_PASSWORD=redis_password
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=500
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_SENTINEL_PASSWORD=redis_sentinel_pass
    ports:
      - "26379:26379"
    depends_on:
      - redis-master
      - redis-slave
