FROM --platform=linux/arm64 arm64v8/openjdk:17-jdk-slim-bullseye

WORKDIR /api/

RUN addgroup --system spring && adduser --system --ingroup spring spring
RUN chown spring:spring /api
USER spring:spring

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} /api/app.jar

COPY run_backend_local_testing.sh /api/run_backend_local_testing.sh

ENTRYPOINT ["/bin/sh", "/api/run_backend_local_testing.sh"]