version: '3.9'
services:
  cardano-explorer-api:
    image: cardano-explorer-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PRIVATE_MVN_REGISTRY_URL=${PRIVATE_MVN_REGISTRY_URL}
        - PRIVATE_MVN_REGISTRY_USER=${PRIVATE_MVN_REGISTRY_USER}
        - PRIVATE_MVN_REGISTRY_PASS=${PRIVATE_MVN_REGISTRY_PASS}
        - SETTINGS_XML_TPL=${SETTINGS_XML_TPL}

    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_MAXIUM_POOL_SIZE=${DB_MAXIUM_POOL_SIZE}

      - REDIS_SENTINEL_MASTER_NAME=${REDIS_SENTINEL_MASTER_NAME}
      - REDIS_SENTINEL_PASSWORD=${REDIS_SENTINEL_PASSWORD}
      - REDIS_SENTINEL_HOST=${REDIS_SENTINEL_HOST}
      - REDIS_SENTINEL_PORT=${REDIS_SENTINEL_PORT}
      - PORT=${PORT}
      - JACKSON_INCLUSION:${JACKSON_INCLUSION}

      - KAFKA_BOOTSTRAP_SERVER=${KAFKA_BOOTSTRAP_SERVER}
      - KAFKA_REPORTS_TOPIC=${KAFKA_REPORTS_TOPIC}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_STORAGE_ENDPOINT=${S3_STORAGE_ENDPOINT}

      - API_CHECK_REWARD_URL=${API_CHECK_REWARD_URL}
      - API_CHECK_POOL_HISTORY_URL=${API_CHECK_POOL_HISTORY_URL}
      - API_CHECK_POOL_INFO_URL=${API_CHECK_POOL_INFO_URL}
      - API_CHECK_EPOCH_STAKE_URL=${API_CHECK_EPOCH_STAKE_URL}
      - API_CHECK_ADA_POTS_URL=${API_CHECK_ADA_POTS_URL}

      - API_NEWS_URL=${API_NEWS_URL}
      - API_NEWS_CACHE_TIME=${API_NEWS_CACHE_TIME}
      - API_MARKET_URL=${API_MARKET_URL}
      - API_MARKET_CACHE_TIME=${API_MARKET_CACHE_TIME}
      - API_CHECK_EPOCH_URL=${API_CHECK_EPOCH_URL}

      - EPOCH_DAYS=${EPOCH_DAYS}
      - REPORT_LIMIT_PER_24HOURS=${REPORT_LIMIT_PER_24HOURS}
      - TOKEN_LOGO_ENDPOINT=${TOKEN_LOGO_ENDPOINT}

      - SHELLEY_GENESIS_FILE=${SHELLEY_GENESIS_FILE}
      - BYRON_GENESIS_FILE=${BYRON_GENESIS_FILE}

    ports:
      - ${PORT}:8080
    volumes:
      - ${LOG_PATH}:/cardano-explorer-api/logs/
