version: '3.9'
services:
  cardano-explorer-api:
    image: cardano-explorer-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PRIVATE_MVN_REGISTRY_URL=${PRIVATE_MVN_REGISTRY_URL}
        - PRIVATE_MVN_REGISTRY_USER=${PRIVATE_MVN_REGISTRY_USER}
        - PRIVATE_MVN_REGISTRY_PASS=${PRIVATE_MVN_REGISTRY_PASS}
        - SETTINGS_XML_TPL=${SETTINGS_XML_TPL}

    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

      - LEDGER_SYNC_HOST=${LEDGER_SYNC_HOST}
      - LEDGER_SYNC_PORT=${LEDGER_SYNC_PORT}
      - LEDGER_SYNC_USER=${LEDGER_SYNC_USER}
      - LEDGER_SYNC_PASSWORD=${LEDGER_SYNC_PASSWORD}
      - LEDGER_SYNC_DB=${LEDGER_SYNC_DB}

      - ANALYTICS_HOST=${ANALYTICS_HOST}
      - ANALYTICS_PORT=${ANALYTICS_PORT}
      - ANALYTICS_USER=${ANALYTICS_USER}
      - ANALYTICS_PASSWORD=${ANALYTICS_PASSWORD}
      - ANALYTICS_DB=${ANALYTICS_DB}

      - DB_SCHEMA=${DB_SCHEMA}
      - DB_MAXIMUM_POOL_SIZE=${DB_MAXIMUM_POOL_SIZE}

      - REDIS_SENTINEL_MASTER_NAME=${REDIS_SENTINEL_MASTER_NAME}
      - REDIS_SENTINEL_PASSWORD=${REDIS_SENTINEL_PASSWORD}
      - REDIS_SENTINEL_HOST=${REDIS_SENTINEL_HOST}
      - REDIS_SENTINEL_PORT=${REDIS_SENTINEL_PORT}
      - PORT=${PORT}

      - KAFKA_BOOTSTRAP_SERVER=${KAFKA_BOOTSTRAP_SERVER}
      - KAFKA_REPORTS_TOPIC=${KAFKA_REPORTS_TOPIC}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_STORAGE_ENDPOINT=${S3_STORAGE_ENDPOINT}

      - API_CHECK_REWARD_URL=${API_CHECK_REWARD_URL}
      - API_CHECK_POOL_HISTORY_URL=${API_CHECK_POOL_HISTORY_URL}
      - API_CHECK_POOL_INFO_URL=${API_CHECK_POOL_INFO_URL}
      - API_CHECK_EPOCH_STAKE_URL=${API_CHECK_EPOCH_STAKE_URL}
      - API_CHECK_ADA_POTS_URL=${API_CHECK_ADA_POTS_URL}

      - API_NEWS_URL=${API_NEWS_URL}
      - API_NEWS_CACHE_TIME=${API_NEWS_CACHE_TIME}
      - API_MARKET_URL=${API_MARKET_URL}
      - API_MARKET_CACHE_TIME=${API_MARKET_CACHE_TIME}
      - API_CHECK_EPOCH_URL=${API_CHECK_EPOCH_URL}

    ports:
      - ${PORT}:8080
    volumes:
      - ${LOG_PATH}:/cardano-explorer-api/logs/
