version: '3.9'
networks:
  default:
    name: infrastructure-net
    external: true

services:
  cardano-explorer-api:
    image: cardano-explorer-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_MAXIUM_POOL_SIZE=${DB_MAXIUM_POOL_SIZE}

      - REDIS_SENTINEL_MASTER_NAME=${REDIS_SENTINEL_MASTER_NAME}
      - REDIS_SENTINEL_PASSWORD=${REDIS_SENTINEL_PASSWORD}
      - REDIS_SENTINEL_HOST=${REDIS_SENTINEL_HOST}
      - REDIS_SENTINEL_PORT=${REDIS_SENTINEL_PORT}
      - PORT=${PORT}

      - KAFKA_BOOTSTRAP_SERVER=${KAFKA_BOOTSTRAP_SERVER}
      - KAFKA_REPORTS_TOPIC=${KAFKA_REPORTS_TOPIC}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_STORAGE_ENDPOINT=${S3_STORAGE_ENDPOINT}

    ports:
      - ${PORT}:8080
    healthcheck:
      test: "curl --fail --silent 172.16.1.230:${PORT}/actuator/health | grep UP || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - $PWD/cardano/volumes/logs/cardano-explorer-api:/cardano-explorer-api/logs/
