version: '3.9'
networks:
  default:
    name: infrastructure-net
    external: true

services:
  cardano-explorer-api:
    container_name: cardano-explorer-api
    image: cardano-explorer-api
    build:
      context: .
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - HOST=${HOST}
      - PORT_DB=${PORT_DB}
      - USERNAME_DB=${USERNAME_DB}
      - PASSWORD_DB=${PASSWORD_DB}
    ports:
      - "8033:8080"
    volumes:
      - $PWD/cardano/volumes/logs/cardano-explorer-api:/cardano-explorer-api/logs/