# Infrastructure domain
multi-datasource: #specified for HikariDataSource
  datasourceLedgerSync:
    hikariConfig:
      jdbcUrl: jdbc:postgresql://${LEDGER_SYNC_HOST:10.4.10.112}:${LEDGER_SYNC_PORT:54323}/${LEDGER_SYNC_DB:explorer_api}?currentSchema=${LEDGER_SYNC_SCHEMA:preprod}
      username: ${LEDGER_SYNC_USER:cardano-read}
      password: ${LEDGER_SYNC_PASSWORD:1}
      driverClassName: org.postgresql.Driver
      poolName: explorer-api-ledgersync-pool
      minimumIdle: 1 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximumPoolSize: ${MAXIMUM_POOL_SIZE:48} #maximum pool size
      idleTimeout: 300000 #maximum idle time for connection
      maxLifetime: 900000 #maximum lifetime in milliseconds of a connection in the pool after it is closed.
      connectionTimeout: 50000 #maximum number of milliseconds that a client will wait for a connection
      autoCommit: false #default auto-commit behavior.
      connectionInitSql: SELECT 1
      dataSourceProperties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  datasourceLedgerSyncAgg:
    hikariConfig:
      jdbcUrl: jdbc:postgresql://${LEDGER_SYNC_AGG_HOST:10.4.10.112}:${LEDGER_SYNC_AGG_PORT:54321}/${LEDGER_SYNC_AGG_DB:explorer_api}?currentSchema=${LEDGER_SYNC_AGG_SCHEMA:preprod}
      username: ${LEDGER_SYNC_AGG_USER:cardano-read}
      password: ${LEDGER_SYNC_AGG_PASSWORD:1}
      driverClassName: org.postgresql.Driver
      poolName: explorer-schedule-ledgersync-agg-pool
      minimumIdle: 1 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximumPoolSize: ${MAXIMUM_POOL_SIZE:48} #maximum pool size
      idleTimeout: 300000 #maximum idle time for connection
      maxLifetime: 900000 #maximum lifetime in milliseconds of a connection in the pool after it is closed.
      connectionTimeout: 50000 #maximum number of milliseconds that a client will wait for a connection
      autoCommit: false #default auto-commit behavior.
      connectionInitSql: SELECT 1
      dataSourceProperties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  datasourceExplorer:
    hikariConfig:
      jdbcUrl: jdbc:postgresql://${EXPLORER_HOST:10.4.10.112}:${EXPLORER_PORT:54323}/${EXPLORER_DB:explorer_api}?currentSchema=${EXPLORER_SCHEMA:preprod}
      username: ${EXPLORER_USER:cardano-master}
      password: ${EXPLORER_PASSWORD:Y2FyZGFuby1kYXRhYmFzZS1tYXN0ZXI=}
      driverClassName: org.postgresql.Driver
      poolName: explorer-api-explorer-pool
      minimumIdle: 1 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximumPoolSize: ${MAXIMUM_POOL_SIZE:48} #maximum pool size
      idleTimeout: 300000 #maximum idle time for connection
      maxLifetime: 900000 #maximum lifetime in milliseconds of a connection in the pool after it is closed.
      connectionTimeout: 50000 #maximum number of milliseconds that a client will wait for a connection
      autoCommit: false #default auto-commit behavior.
      connectionInitSql: SELECT 1
      dataSourceProperties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

spring:
  # JPA specific configs
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
  flyway:
    enabled: false
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
  jackson:
    default-property-inclusion: ${JACKSON_INCLUSION:ALWAYS}

redis:
  databaseIndex: 0
  master: ${REDIS_SENTINEL_MASTER_NAME:mymaster}
  password: ${REDIS_SENTINEL_PASSWORD:redis_sentinel_pass}
  testOnBorrow: false
  maxTotal: 10
  maxIdle: 5
  minIdle: 3
  testOnReturn: false
  testWhileIdle: false
  sentinels:
    - host: ${REDIS_SENTINEL_HOST:127.0.0.1}
      port: ${REDIS_SENTINEL_PORT:26379}

application:
  network: ${NETWORK:mainnet}
  epoch:
    days: ${EPOCH_DAYS:5}
  api.news:
    interval-time: ${API_NEWS_CACHE_TIME:120}
    base-url: ${API_NEWS_URL}
  api:
    check-reward:
      base-url: ${API_CHECK_REWARD_URL:http://localhost:8888/api/v1/rewards/fetch}
    check-pool-history:
      base-url: ${API_CHECK_POOL_HISTORY_URL:http://localhost:8888/api/v1/pool-history/fetch}
    check-pool-info:
      base-url: ${API_CHECK_POOL_INFO_URL:http://localhost:8888/api/v1/pool-info/fetch}
    check-epoch-stake:
      base-url: ${API_CHECK_EPOCH_STAKE_URL:http://localhost:8888/api/v1/epoch-stake/fetch}
    check-ada-pots:
      base-url: ${API_CHECK_ADA_POTS_URL:http://localhost:8888/api/v1/ada-pots/fetch}
    check-epoch:
      base-url: ${API_CHECK_EPOCH_URL:http://localhost:8888/api/v1/epochs/fetch}
  token-logo-endpoint: ${TOKEN_LOGO_ENDPOINT:http://localhost:9001}
  healthcheck:
    block-time-threshold: ${BLOCK_TIME_THRESHOLD_IN_SECOND:240}
    inserted-time-threshold: ${INSERTED_TIME_THRESHOLD_IN_SECOND:2400}
  api.bolnisi:
    off-chain: ${API_BOLNISI_OFFCHAIN_URL:https://offchain.pro.cf-bolnisi-mainnet.eu-west-1.bnwa.metadata.dev.cf-deployments.org/api/v1/storage/objectUrl/georgian-wine/{cid}}
    public-key:
      primary: ${API_BOLNISI_PUBLIC_KEY_PRIMARY_URL:https://cardano.mepa.gov.ge/api/v1/publickeys/winery/{wineryId}/v/0}
      fallback: ${API_BOLNISI_PUBLIC_KEY_FALLBACK_URL:https://api.pro.cf-bolnisi-mainnet.eu-west-1.bnwa.metadata.dev.cf-deployments.org/api/v1/pubkeys/{wineryId}/v/0}

springdoc:
  api-docs.path: /apidocs
  show-actuator: true

server:
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,prometheus,info,sync-status"
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
    info:
      enabled: true
    sync-status:
      enabled: true

  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
      percentiles-histogram:
        http.server.requests: true

rsa:
  key:
    public-key-str: ${RSA_PUBLIC_KEY_AUTH}

keycloak:
  role:
    path: ${AUTH_FILE_PATH:classpath:permission/policy.json}

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY:miniominio}
      secret-key: ${S3_SECRET_KEY:sekritsekrit}
    region:
      static: ${S3_REGION:null}
    s3:
      bucket:
        name: ${S3_BUCKET_NAME:cardano-explorer-api-storage}
      path-style:
        enabled: ${S3_PATH_STYLE_ENABLED:true}
      endpoint: ${S3_STORAGE_ENDPOINT}

logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

---
genesis:
  shelley: ${SHELLEY_GENESIS_FILE:src/main/resources/networks/${SCHEMA:mainnet}/shelley-genesis.json}
  byron: ${BYRON_GENESIS_FILE:src/main/resources/networks/${SCHEMA:mainnet}/byron-genesis.json}
  conway: ${CONWAY_GENESIS_FILE:src/main/resources/networks/${SCHEMA:sanchonet}/conway-genesis.json}