# Infrastructure domain
infrastructure:
  host: 10.4.10.112

spring:
  # Datasource specific configs
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${infrastructure.host}:54321/explorer?currentSchema=mainnet
    username: cardano_read
    password: 1
    driver-class-name: org.postgresql.Driver
    # Hikari specific configs
    hikari:
      pool-name: explorer-api-pool
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 20 #maximum pool size
      idle-timeout: 300000 #maximum idle time for connection
      max-lifetime: 900000 #maximum lifetime in milliseconds of a connection in the pool after it is closed.
      connection-timeout: 50000 #maximum number of milliseconds that a client will wait for a connection
      auto-commit: false #default auto-commit behavior.
      connection-init-sql: SELECT 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  # JPA specific configs
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: mainnet
        show_sql: true
        format_sql: true
  flyway:
    enabled: false
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100

redis:
  databaseIndex: 0
  master: ${REDIS_MASTER_NAME:mymaster}
  password: ${REDIS_SENTINEL_PASS:redis_sentinel_pass}
  testOnBorrow: false
  maxTotal: 10
  maxIdle: 5
  minIdle: 3
  testOnReturn: false
  testWhileIdle: false
  sentinels:
    - host: ${REDIS_SENTINEL_HOST:127.0.0.1}
      port: 26379

cloud:
  aws:
    credentials:
      access-key: ${MINIO_ACCESS_KEY:miniominio}
      secret-key: ${MINIO_SECRET_KEY:sekritsekrit}
    region:
      static: null
    s3:
      bucket:
        name: ${BUCKET_NAME:cardano-explorer-api-storage}
      path-style:
        enabled: true
      endpoint: ${STORAGE_ENDPOINT:http://localhost:9001}
application:
  network: ${SCHEMA:mainnet}
  api.coin.gecko.market:
    interval-time: 60
    base-url: https://api.coingecko.com/api/v3/coins/markets?ids=cardano&vs_currency=%s
  time-zone: ${TIME_ZONE:GMT+1}

rsa:
  key:
    path: /key/public_key