# Infrastructure domain
infrastructure:
  host: 172.16.1.230

spring:
  # Datasource specific configs
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${infrastructure.host}:54321/explorer_api?currentSchema=dev
    username: explorer_api_read
    password: MTIzNDU2NzhhQUA=READ
    driver-class-name: org.postgresql.Driver
    # Hikari specific configs
    hikari:
      pool-name: explorer-api-pool
      minimum-idle: 1 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 1 #maximum pool size
      idle-timeout: 300000 #maximum idle time for connection
      max-lifetime: 900000 #maximum lifetime in milliseconds of a connection in the pool after it is closed.
      connection-timeout: 50000 #maximum number of milliseconds that a client will wait for a connection
      auto-commit: false #default auto-commit behavior.
      connection-init-sql: SELECT 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  # JPA specific configs
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: dev
        show_sql: true
        format_sql: true
  flyway:
    enabled: false
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 50

redis:
  databaseIndex: 0
  master: ${REDIS_MASTER_NAME:mymaster}
  password: ${REDIS_SENTINEL_PASS:redis_sentinel_pass}
  testOnBorrow: false
  maxTotal: 10
  maxIdle: 5
  minIdle: 3
  testOnReturn: false
  testWhileIdle: false
  sentinels:
    - host: ${REDIS_SENTINEL_HOST:127.0.0.1}
      port: 26379


application:
  network: ${SCHEMA:mainnet}
  api.coin.gecko.market:
    interval-time: 15
    base-url: https://api.coingecko.com/api/v3/coins/markets?ids=cardano&vs_currency=%s
