name: CI/CD for cardano-explorer-api

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Entering to Github Runner
        run: echo "Entering to Github Runner"
      - name: Copy configuration file
        run: cp -r /home/sotatek/jenkins-cardano/configs/cardano-explorer-api ./.m2/settings.xml
      - name: Building
        run: docker build -t cardano-explorer-api .

  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy Mainnet
        run: docker-compose --env-file /home/sotatek/jenkins-cardano/configs/cardano-explorer-api/mainnet.env -p mainnet up -d
      - name: Deploy Preprod
        run: docker-compose --env-file /home/sotatek/jenkins-cardano/configs/cardano-explorer-api/preprod.env -p preprod up -d
      - name: Purging unused Images
        run: docker images -f "dangling=true" -q --no-trunc | xargs --no-run-if-empty docker rmi &>/dev/null
