name: CI/CD for cardano-explorer-api

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

env:
  NAMESPACE: develop

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Entering to Github Runner
        run: 'echo "Entering to Github Runner" '

      - name: Copy configuration file
        shell: bash
      - run: "cp /home/sotatek/jenkins-cardano/configs/cardano-explorer-api ./.m2/settings.xml"

      - name: Building
        shell: bash
      - run: "docker build -t cardano-explorer-api ."
      
      

  deploy:
    runs-on: self-hosted
    needs: [build]

    steps:
      - name: Deploy Mainnet
      - uses: actions/checkout@v3
        shell: bash
      - run: "docker-compose --env-file /home/sotatek/jenkins-cardano/configs/cardano-explorer-api/mainnet.env -p mainnet up -d"


      - name: Deploy Preprod
        shell: bash
      - run: "docker-compose --env-file /home/sotatek/jenkins-cardano/configs/cardano-explorer-api/preprod.env -p preprod up -d"

      - name: Puring unsed Images
        shell: bash
      - run: 'docker images -f "dangling=true" -q --no-trunc | xargs --no-run-if-empty docker rmi &>/dev/null'
