name: Run Tests

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

env:
  PRIVATE_MVN_REGISTRY_TOKEN: ${{ secrets.GITLAB_PKG_REGISTRY_TOKEN }}
  PRIVATE_MVN_REGISTRY_URL: ${{ secrets.GITLAB_MAVEN_REGISTRY_URL }}
  PRIVATE_MVN_REGISTRY_USER: ${{ secrets.PRIVATE_MVN_REGISTRY_USER }}
  PRIVATE_MVN_REGISTRY_PASS: ${{ secrets.PRIVATE_MVN_REGISTRY_PASS }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      - name: Setup depends
        run: |
          pip install yq

      - name: Setup maven settings.xml
        run: | 
          envsubst < ./.m2/settings.default.xml.tpl > ./.m2/settings.xml

      - name: Build
        run: |
          mvn --batch-mode --update-snapshots clean package -DskipTests

      - name: Test
        run: |
          mvn --batch-mode --update-snapshots -Dmaven.test.failure.ignore=true test
